# -*- coding: utf-8 -*-
"""search_youtube_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIcH5Ue3yNEnibam2M2V0x54hG8Jt85Q
"""

import json
import urllib.request
import urllib.error
from getpass import getpass

client_id = getpass("Naver Client ID 입력: ").strip()
client_secret = getpass("Naver Client Secret 입력: ").strip()

url = "https://openapi.naver.com/v1/datalab/search"

body = {
    "startDate": "2026-05-10",
    "endDate": "2026-06-08",
    "timeUnit": "date",
    "keywordGroups": [
        {"groupName": "거제", "keywords": ["거제"]},
        {"groupName": "리센느", "keywords": ["리센느"]},
        {"groupName": "선거", "keywords": ["선거"]},
        {"groupName": "삼성전자", "keywords": ["삼성전자"]},
        {"groupName": "AI", "keywords": ["AI"]}
    ]
}

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id", client_id)
request.add_header("X-Naver-Client-Secret", client_secret)
request.add_header("Content-Type", "application/json")

try:
    response = urllib.request.urlopen(
        request,
        data=json.dumps(body).encode("utf-8")
    )

    result = json.loads(response.read().decode("utf-8"))

    with open("naver_datalab_sample.json", "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    print("저장 완료: naver_datalab_sample.json")
    print(json.dumps(result, ensure_ascii=False, indent=2)[:1000])

except urllib.error.HTTPError as e:
    print("HTTP Error:", e.code)
    print(e.read().decode("utf-8"))

import json
import pandas as pd

with open("naver_datalab_sample.json", "r", encoding="utf-8") as f:
    result = json.load(f)

rows = []

for item in result["results"]:
    keyword = item["title"]
    data_points = item["data"]

    ratios = [point["ratio"] for point in data_points]

    avg_ratio = sum(ratios) / len(ratios) if ratios else 0
    max_ratio = max(ratios) if ratios else 0
    max_date = data_points[ratios.index(max_ratio)]["period"] if ratios else None

    rows.append({
        "keyword": keyword,
        "naver_interest": round(avg_ratio, 4),
        "naver_max_interest": round(max_ratio, 4),
        "naver_max_date": max_date
    })

naver_summary = pd.DataFrame(rows)

naver_summary.to_csv(
    "naver_datalab_summary_sample.csv",
    index=False,
    encoding="utf-8-sig"
)

naver_summary

import requests
import pandas as pd
from datetime import datetime, timezone
from getpass import getpass

youtube_api_key = getpass("YouTube API Key 입력: ").strip()

keywords = ["거제", "리센느", "선거", "삼성전자", "AI"]

published_after = "2026-05-10T00:00:00Z"
published_before = "2026-06-09T00:00:00Z"

search_rows = []

for keyword in keywords:
    search_url = "https://www.googleapis.com/youtube/v3/search"
    params = {
        "part": "snippet",
        "q": keyword,
        "type": "video",
        "order": "viewCount",
        "maxResults": 5,
        "publishedAfter": published_after,
        "publishedBefore": published_before,
        "regionCode": "KR",
        "relevanceLanguage": "ko",
        "key": youtube_api_key
    }

    response = requests.get(search_url, params=params)
    data = response.json()

    if "error" in data:
        print("ERROR:", keyword, data["error"])
        continue

    for item in data.get("items", []):
        video_id = item["id"]["videoId"]
        snippet = item["snippet"]

        search_rows.append({
            "keyword": keyword,
            "video_id": video_id,
            "title": snippet.get("title"),
            "channel_title": snippet.get("channelTitle"),
            "published_at": snippet.get("publishedAt")
        })

youtube_search_df = pd.DataFrame(search_rows)
youtube_search_df.to_csv("youtube_search_sample.csv", index=False, encoding="utf-8-sig")

print("검색 결과 저장 완료: youtube_search_sample.csv")
youtube_search_df

import requests
import pandas as pd
from datetime import datetime, timezone

video_ids = youtube_search_df["video_id"].dropna().unique().tolist()

stats_rows = []

for i in range(0, len(video_ids), 50):
    batch_ids = video_ids[i:i+50]

    videos_url = "https://www.googleapis.com/youtube/v3/videos"
    params = {
        "part": "snippet,statistics,contentDetails",
        "id": ",".join(batch_ids),
        "key": youtube_api_key
    }

    response = requests.get(videos_url, params=params)
    data = response.json()

    if "error" in data:
        print("ERROR:", data["error"])
        continue

    for item in data.get("items", []):
        snippet = item.get("snippet", {})
        statistics = item.get("statistics", {})

        stats_rows.append({
            "video_id": item.get("id"),
            "title": snippet.get("title"),
            "channel_title": snippet.get("channelTitle"),
            "published_at": snippet.get("publishedAt"),
            "category_id": snippet.get("categoryId"),
            "view_count": int(statistics.get("viewCount", 0)),
            "like_count": int(statistics.get("likeCount", 0)) if "likeCount" in statistics else None,
            "comment_count": int(statistics.get("commentCount", 0)) if "commentCount" in statistics else None
        })

youtube_stats_df = pd.DataFrame(stats_rows)

youtube_stats_df.to_csv("youtube_video_stats_sample.csv", index=False, encoding="utf-8-sig")

print("영상 통계 저장 완료: youtube_video_stats_sample.csv")
youtube_stats_df

import pandas as pd
from datetime import datetime, timezone
import numpy as np

# Google Trends 요약 직접 입력
google_summary = pd.DataFrame([
    {"keyword": "거제", "google_interest": 1.1333},
    {"keyword": "리센느", "google_interest": 1.8333},
    {"keyword": "선거", "google_interest": 14.8333},
    {"keyword": "삼성전자", "google_interest": 26.9333},
    {"keyword": "AI", "google_interest": 62.3000},
])

# Naver DataLab 요약 읽기
naver_summary = pd.read_csv("naver_datalab_summary_sample.csv")

# YouTube 검색 결과와 통계 합치기
youtube_merged = youtube_search_df[["keyword", "video_id"]].merge(
    youtube_stats_df,
    on="video_id",
    how="left"
)

# 날짜 처리
collected_at = datetime.now(timezone.utc)

youtube_merged["published_at_dt"] = pd.to_datetime(youtube_merged["published_at"], utc=True)
youtube_merged["collected_at"] = collected_at.isoformat()

youtube_merged["days_since_upload"] = (
    collected_at - youtube_merged["published_at_dt"]
).dt.days

youtube_merged["days_since_upload"] = youtube_merged["days_since_upload"].replace(0, 1)

youtube_merged["views_per_day"] = (
    youtube_merged["view_count"] / youtube_merged["days_since_upload"]
)

youtube_merged["is_million_view"] = youtube_merged["view_count"] >= 1_000_000

# 검색 관심도 붙이기
youtube_merged = youtube_merged.merge(google_summary, on="keyword", how="left")
youtube_merged = youtube_merged.merge(
    naver_summary[["keyword", "naver_interest"]],
    on="keyword",
    how="left"
)

youtube_merged.to_csv("youtube_trends_merged_sample.csv", index=False, encoding="utf-8-sig")

youtube_merged.head()

keyword_summary = youtube_merged.groupby("keyword").agg(
    google_interest=("google_interest", "first"),
    naver_interest=("naver_interest", "first"),
    video_count=("video_id", "nunique"),
    avg_view_count=("view_count", "mean"),
    median_view_count=("view_count", "median"),
    avg_like_count=("like_count", "mean"),
    avg_comment_count=("comment_count", "mean"),
    million_view_count=("is_million_view", "sum"),
    avg_views_per_day=("views_per_day", "mean")
).reset_index()

keyword_summary["million_view_ratio"] = (
    keyword_summary["million_view_count"] / keyword_summary["video_count"]
)

keyword_summary.to_csv("keyword_summary_sample.csv", index=False, encoding="utf-8-sig")

keyword_summary

corr_cols = [
    "google_interest",
    "naver_interest",
    "avg_view_count",
    "avg_views_per_day",
    "million_view_ratio",
    "avg_like_count",
    "avg_comment_count"
]

corr_result = keyword_summary[corr_cols].corr()

corr_result.to_csv("correlation_sample.csv", encoding="utf-8-sig")

corr_result

import json
import urllib.request
import urllib.error
import pandas as pd
from getpass import getpass

client_id = getpass("Naver Client ID 입력: ").strip()
client_secret = getpass("Naver Client Secret 입력: ").strip()

url = "https://openapi.naver.com/v1/datalab/search"

groups = {
    "group1": [
        {"groupName": "삼성", "keywords": ["삼성"]},
        {"groupName": "AI", "keywords": ["AI"]},
        {"groupName": "반도체", "keywords": ["반도체"]},
        {"groupName": "엔비디아", "keywords": ["엔비디아"]},
        {"groupName": "환율", "keywords": ["환율"]}
    ],
    "group2": [
        {"groupName": "삼성", "keywords": ["삼성"]},
        {"groupName": "선거", "keywords": ["선거"]},
        {"groupName": "대통령", "keywords": ["대통령"]},
        {"groupName": "대선", "keywords": ["대선"]},
        {"groupName": "국회", "keywords": ["국회"]}
    ],
    "group3": [
        {"groupName": "삼성", "keywords": ["삼성"]},
        {"groupName": "여론조사", "keywords": ["여론조사"]},
        {"groupName": "리센느", "keywords": ["리센느"]},
        {"groupName": "아이브", "keywords": ["아이브"]},
        {"groupName": "에스파", "keywords": ["에스파"]}
    ],
    "group4": [
        {"groupName": "삼성", "keywords": ["삼성"]},
        {"groupName": "뉴진스", "keywords": ["뉴진스"]},
        {"groupName": "르세라핌", "keywords": ["르세라핌"]},
        {"groupName": "충주", "keywords": ["충주"]},
        {"groupName": "여수", "keywords": ["여수"]}
    ],
    "group5": [
        {"groupName": "삼성", "keywords": ["삼성"]},
        {"groupName": "서울", "keywords": ["서울"]},
        {"groupName": "거제", "keywords": ["거제"]},
        {"groupName": "부산", "keywords": ["부산"]}
    ]
}

all_results = {}

for group_name, keyword_groups in groups.items():
    body = {
        "startDate": "2026-05-10",
        "endDate": "2026-06-08",
        "timeUnit": "date",
        "keywordGroups": keyword_groups
    }

    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id", client_id)
    request.add_header("X-Naver-Client-Secret", client_secret)
    request.add_header("Content-Type", "application/json")

    try:
        response = urllib.request.urlopen(
            request,
            data=json.dumps(body).encode("utf-8")
        )

        result = json.loads(response.read().decode("utf-8"))
        all_results[group_name] = result

        file_name = f"naver_datalab_{group_name}.json"
        with open(file_name, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)

        print(f"저장 완료: {file_name}")

    except urllib.error.HTTPError as e:
        print(f"{group_name} HTTP Error:", e.code)
        print(e.read().decode("utf-8"))

print("Naver DataLab 5개 그룹 수집 완료")

summary_rows = []

for group_name, result in all_results.items():
    for item in result["results"]:
        keyword = item["title"]
        data_points = item["data"]
        ratios = [point["ratio"] for point in data_points]

        avg_ratio = sum(ratios) / len(ratios) if ratios else 0
        max_ratio = max(ratios) if ratios else 0
        max_date = data_points[ratios.index(max_ratio)]["period"] if ratios else None

        summary_rows.append({
            "group": group_name,
            "keyword": keyword,
            "naver_raw_interest": round(avg_ratio, 6),
            "naver_max_interest": round(max_ratio, 6),
            "naver_max_date": max_date
        })

naver_raw_summary = pd.DataFrame(summary_rows)

# group1의 삼성 평균을 기준점으로 사용
reference_samsung = naver_raw_summary[
    (naver_raw_summary["group"] == "group1") &
    (naver_raw_summary["keyword"] == "삼성")
]["naver_raw_interest"].iloc[0]

# 각 그룹별 삼성 평균
group_samsung = naver_raw_summary[
    naver_raw_summary["keyword"] == "삼성"
][["group", "naver_raw_interest"]].rename(
    columns={"naver_raw_interest": "group_samsung_interest"}
)

naver_summary = naver_raw_summary.merge(group_samsung, on="group", how="left")

naver_summary["naver_anchor_factor"] = (
    reference_samsung / naver_summary["group_samsung_interest"]
)

naver_summary["naver_interest"] = (
    naver_summary["naver_raw_interest"] * naver_summary["naver_anchor_factor"]
)

# 삼성은 중복되므로 group1의 삼성만 남기고 나머지 삼성 제거
naver_summary_final = naver_summary[
    (naver_summary["keyword"] != "삼성") |
    ((naver_summary["keyword"] == "삼성") & (naver_summary["group"] == "group1"))
].copy()

naver_summary_final["naver_interest"] = naver_summary_final["naver_interest"].round(6)

naver_summary_final.to_csv(
    "naver_datalab_20keywords_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

naver_summary_final.sort_values("naver_interest", ascending=False)

import pandas as pd
from pathlib import Path

google_files = [
    "google_trends_group1.csv",
    "google_trends_group2.csv",
    "google_trends_group3.csv",
    "google_trends_group4.csv",
    "google_trends_group5.csv"
]

google_rows = []

for idx, file_name in enumerate(google_files, start=1):
    group_name = f"group{idx}"
    df = pd.read_csv(file_name)

    for col in df.columns:
        if col != "Time":
            values = df[col]
            google_rows.append({
                "group": group_name,
                "keyword": col,
                "google_raw_interest": values.mean(),
                "google_max_interest": values.max(),
                "google_max_date": df.loc[values.idxmax(), "Time"]
            })

google_raw_summary = pd.DataFrame(google_rows)

# group1의 삼성 평균을 기준점으로 사용
reference_samsung = google_raw_summary[
    (google_raw_summary["group"] == "group1") &
    (google_raw_summary["keyword"] == "삼성")
]["google_raw_interest"].iloc[0]

group_samsung = google_raw_summary[
    google_raw_summary["keyword"] == "삼성"
][["group", "google_raw_interest"]].rename(
    columns={"google_raw_interest": "group_samsung_google"}
)

google_summary = google_raw_summary.merge(group_samsung, on="group", how="left")

google_summary["google_anchor_factor"] = (
    reference_samsung / google_summary["group_samsung_google"]
)

google_summary["google_interest"] = (
    google_summary["google_raw_interest"] * google_summary["google_anchor_factor"]
)

# 삼성은 중복되므로 group1의 삼성만 남김
google_summary_final = google_summary[
    (google_summary["keyword"] != "삼성") |
    ((google_summary["keyword"] == "삼성") & (google_summary["group"] == "group1"))
].copy()

google_summary_final["google_interest"] = google_summary_final["google_interest"].round(6)

google_summary_final.to_csv(
    "google_trends_20keywords_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

google_summary_final.sort_values("google_interest", ascending=False)

naver_summary = pd.read_csv("naver_datalab_20keywords_summary.csv")

search_interest = google_summary_final[[
    "keyword",
    "google_interest",
    "google_raw_interest",
    "google_max_interest",
    "google_max_date"
]].merge(
    naver_summary[[
        "keyword",
        "naver_interest",
        "naver_raw_interest",
        "naver_max_interest",
        "naver_max_date"
    ]],
    on="keyword",
    how="outer"
)

category_map = {
    "AI": "IT/경제",
    "삼성": "IT/경제",
    "반도체": "IT/경제",
    "엔비디아": "IT/경제",
    "환율": "IT/경제",

    "선거": "정치/사회",
    "대통령": "정치/사회",
    "대선": "정치/사회",
    "국회": "정치/사회",
    "여론조사": "정치/사회",

    "리센느": "엔터/문화",
    "아이브": "엔터/문화",
    "에스파": "엔터/문화",
    "뉴진스": "엔터/문화",
    "르세라핌": "엔터/문화",

    "충주": "지역",
    "여수": "지역",
    "서울": "지역",
    "거제": "지역",
    "부산": "지역"
}

search_interest["category"] = search_interest["keyword"].map(category_map)

search_interest.to_csv(
    "search_interest_20keywords.csv",
    index=False,
    encoding="utf-8-sig"
)

search_interest.sort_values("google_interest", ascending=False)

import requests
import pandas as pd
from getpass import getpass
from datetime import datetime, timezone

youtube_api_key = getpass("YouTube API Key 입력: ").strip()

keywords = [
    "AI", "삼성", "반도체", "엔비디아", "환율",
    "선거", "대통령", "대선", "국회", "여론조사",
    "리센느", "아이브", "에스파", "뉴진스", "르세라핌",
    "충주", "여수", "서울", "거제", "부산"
]

published_after = "2026-05-10T00:00:00Z"
published_before = "2026-06-09T00:00:00Z"

search_rows = []

for keyword in keywords:
    search_url = "https://www.googleapis.com/youtube/v3/search"

    params = {
        "part": "snippet",
        "q": keyword,
        "type": "video",
        "order": "viewCount",
        "maxResults": 30,
        "publishedAfter": published_after,
        "publishedBefore": published_before,
        "regionCode": "KR",
        "relevanceLanguage": "ko",
        "key": youtube_api_key
    }

    response = requests.get(search_url, params=params)
    data = response.json()

    if "error" in data:
        print("ERROR:", keyword, data["error"])
        continue

    for item in data.get("items", []):
        video_id = item["id"]["videoId"]
        snippet = item["snippet"]

        search_rows.append({
            "keyword": keyword,
            "video_id": video_id,
            "title_from_search": snippet.get("title"),
            "channel_title_from_search": snippet.get("channelTitle"),
            "published_at_from_search": snippet.get("publishedAt")
        })

youtube_search_df = pd.DataFrame(search_rows)

youtube_search_df.to_csv(
    "youtube_search_20keywords.csv",
    index=False,
    encoding="utf-8-sig"
)

print("검색 결과 저장 완료:", len(youtube_search_df), "rows")
youtube_search_df.head()

import requests
import pandas as pd

video_ids = youtube_search_df["video_id"].dropna().unique().tolist()

stats_rows = []

for i in range(0, len(video_ids), 50):
    batch_ids = video_ids[i:i+50]

    videos_url = "https://www.googleapis.com/youtube/v3/videos"
    params = {
        "part": "snippet,statistics,contentDetails",
        "id": ",".join(batch_ids),
        "key": youtube_api_key
    }

    response = requests.get(videos_url, params=params)
    data = response.json()

    if "error" in data:
        print("ERROR:", data["error"])
        continue

    for item in data.get("items", []):
        snippet = item.get("snippet", {})
        statistics = item.get("statistics", {})

        stats_rows.append({
            "video_id": item.get("id"),
            "title": snippet.get("title"),
            "channel_title": snippet.get("channelTitle"),
            "published_at": snippet.get("publishedAt"),
            "category_id": snippet.get("categoryId"),
            "default_language": snippet.get("defaultLanguage"),
            "default_audio_language": snippet.get("defaultAudioLanguage"),
            "view_count": int(statistics.get("viewCount", 0)),
            "like_count": int(statistics.get("likeCount", 0)) if "likeCount" in statistics else None,
            "comment_count": int(statistics.get("commentCount", 0)) if "commentCount" in statistics else None
        })

youtube_stats_df = pd.DataFrame(stats_rows)

youtube_stats_df.to_csv(
    "youtube_video_stats_20keywords.csv",
    index=False,
    encoding="utf-8-sig"
)

print("영상 통계 저장 완료:", len(youtube_stats_df), "unique videos")
youtube_stats_df.head()

from datetime import datetime, timezone
import numpy as np

# 검색 결과와 통계 합치기
youtube_merged = youtube_search_df[["keyword", "video_id"]].merge(
    youtube_stats_df,
    on="video_id",
    how="left"
)

# 검색 관심도 붙이기
youtube_merged = youtube_merged.merge(
    search_interest[["keyword", "category", "google_interest", "naver_interest"]],
    on="keyword",
    how="left"
)

# 날짜 및 보정 지표 계산
collected_at = datetime.now(timezone.utc)

youtube_merged["published_at_dt"] = pd.to_datetime(
    youtube_merged["published_at"],
    utc=True
)

youtube_merged["collected_at"] = collected_at.isoformat()

youtube_merged["days_since_upload"] = (
    collected_at - youtube_merged["published_at_dt"]
).dt.days

youtube_merged["days_since_upload"] = youtube_merged["days_since_upload"].replace(0, 1)

youtube_merged["views_per_day"] = (
    youtube_merged["view_count"] / youtube_merged["days_since_upload"]
)

youtube_merged["is_million_view"] = youtube_merged["view_count"] >= 1_000_000

youtube_merged.to_csv(
    "youtube_trends_merged_20keywords.csv",
    index=False,
    encoding="utf-8-sig"
)

print("병합 데이터 저장 완료:", len(youtube_merged), "rows")
youtube_merged.head()

keyword_summary = youtube_merged.groupby(["category", "keyword"]).agg(
    google_interest=("google_interest", "first"),
    naver_interest=("naver_interest", "first"),
    video_count=("video_id", "nunique"),
    avg_view_count=("view_count", "mean"),
    median_view_count=("view_count", "median"),
    avg_like_count=("like_count", "mean"),
    avg_comment_count=("comment_count", "mean"),
    million_view_count=("is_million_view", "sum"),
    avg_views_per_day=("views_per_day", "mean"),
    median_views_per_day=("views_per_day", "median")
).reset_index()

keyword_summary["million_view_ratio"] = (
    keyword_summary["million_view_count"] / keyword_summary["video_count"]
)

keyword_summary.to_csv(
    "keyword_summary_20keywords.csv",
    index=False,
    encoding="utf-8-sig"
)

keyword_summary.sort_values("avg_views_per_day", ascending=False)

category_summary = youtube_merged.groupby("category").agg(
    keyword_count=("keyword", "nunique"),
    video_count=("video_id", "nunique"),
    avg_view_count=("view_count", "mean"),
    median_view_count=("view_count", "median"),
    avg_like_count=("like_count", "mean"),
    avg_comment_count=("comment_count", "mean"),
    million_view_count=("is_million_view", "sum"),
    avg_views_per_day=("views_per_day", "mean"),
    median_views_per_day=("views_per_day", "median")
).reset_index()

category_summary["million_view_ratio"] = (
    category_summary["million_view_count"] / category_summary["video_count"]
)

category_summary.to_csv(
    "category_summary_20keywords.csv",
    index=False,
    encoding="utf-8-sig"
)

category_summary.sort_values("avg_views_per_day", ascending=False)

corr_cols = [
    "google_interest",
    "naver_interest",
    "avg_view_count",
    "avg_views_per_day",
    "million_view_ratio",
    "avg_like_count",
    "avg_comment_count"
]

correlation_result = keyword_summary[corr_cols].corr()

correlation_result.to_csv(
    "correlation_20keywords.csv",
    encoding="utf-8-sig"
)

correlation_result

!pip install pandas requests tqdm

import os
import json
import time
import requests
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timezone

API_KEY = "YOUR_YOUTUBE_API_KEY_HERE"

VIDEO_STATS_CSV = "youtube_video_stats_20keywords.csv"
OUT_JSONL = "youtube_comments_raw.jsonl"
OUT_SUMMARY = "youtube_comments_summary.csv"

TARGET_MB = 120
MAX_PAGES_PER_VIDEO = 30
SLEEP_SEC = 0.05

df = pd.read_csv(VIDEO_STATS_CSV)

required_cols = ["video_id"]
for col in required_cols:
    if col not in df.columns:
        raise ValueError(f"필수 컬럼이 없습니다: {col}")

if "comment_count" in df.columns:
    df["comment_count"] = pd.to_numeric(df["comment_count"], errors="coerce").fillna(0)
    df = df.sort_values("comment_count", ascending=False)

df = df.drop_duplicates(subset=["video_id"]).reset_index(drop=True)

def file_size_mb(path):
    if not os.path.exists(path):
        return 0
    return os.path.getsize(path) / (1024 * 1024)

def get_comments(video_id, page_token=None):
    url = "https://www.googleapis.com/youtube/v3/commentThreads"
    params = {
        "part": "snippet,replies",
        "videoId": video_id,
        "maxResults": 100,
        "order": "relevance",
        "textFormat": "plainText",
        "key": AIzaSyAJ_x9HFan3L6VkwSsA9rmHKOGVsXKH1wI
    }
    if page_token:
        params["pageToken"] = page_token

    r = requests.get(url, params=params, timeout=30)
    return r

summary = []
total_comments = 0
skipped_videos = 0
quota_or_error = 0

with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for _, row in tqdm(df.iterrows(), total=len(df)):
        video_id = row["video_id"]
        keyword = row.get("keyword", "")
        category = row.get("category", "")
        title = row.get("title", "")
        channel_title = row.get("channel_title", "")

        page_token = None
        video_comment_count = 0

        for page in range(MAX_PAGES_PER_VIDEO):
            if file_size_mb(OUT_JSONL) >= TARGET_MB:
                break

            try:
                r = get_comments(video_id, page_token)
                if r.status_code != 200:
                    quota_or_error += 1
                    break

                data = r.json()
                items = data.get("items", [])

                if not items:
                    skipped_videos += 1
                    break

                for item in items:
                    snippet = item.get("snippet", {})
                    top = snippet.get("topLevelComment", {})
                    top_snippet = top.get("snippet", {})

                    record = {
                        "fetched_at": datetime.now(timezone.utc).isoformat(),
                        "keyword": keyword,
                        "category": category,
                        "video_id": video_id,
                        "video_title": title,
                        "channel_title": channel_title,
                        "comment_id": top.get("id"),
                        "comment_author": top_snippet.get("authorDisplayName"),
                        "comment_text": top_snippet.get("textDisplay"),
                        "comment_like_count": top_snippet.get("likeCount"),
                        "comment_published_at": top_snippet.get("publishedAt"),
                        "comment_updated_at": top_snippet.get("updatedAt"),
                        "reply_count": snippet.get("totalReplyCount"),
                        "raw_json": item
                    }

                    f.write(json.dumps(record, ensure_ascii=False) + "\n")
                    video_comment_count += 1
                    total_comments += 1

                page_token = data.get("nextPageToken")
                if not page_token:
                    break

                time.sleep(SLEEP_SEC)

            except Exception as e:
                quota_or_error += 1
                break

        summary.append({
            "video_id": video_id,
            "keyword": keyword,
            "category": category,
            "title": title,
            "channel_title": channel_title,
            "collected_comments": video_comment_count
        })

        if file_size_mb(OUT_JSONL) >= TARGET_MB:
            break

summary_df = pd.DataFrame(summary)
summary_df.to_csv(OUT_SUMMARY, index=False, encoding="utf-8-sig")

print("수집 완료")
print("raw jsonl:", OUT_JSONL, round(file_size_mb(OUT_JSONL), 2), "MB")
print("summary csv:", OUT_SUMMARY)
print("total_comments:", total_comments)
print("processed_videos:", len(summary))
print("skipped_videos:", skipped_videos)
print("quota_or_error:", quota_or_error)



import os
for f in ["youtube_comments_raw.jsonl", "youtube_comments_summary.csv"]:
    print(f, round(os.path.getsize(f) / (1024 * 1024), 2), "MB")

import os
import json
import time
import requests
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timezone

API_KEY = "AIzaSyAJ_x9HFan3L6VkwSsA9rmHKOGVsXKH1wI"

VIDEO_STATS_CSV = "youtube_video_stats_20keywords.csv"
OUT_JSONL = "youtube_comments_raw.jsonl"
OUT_SUMMARY = "youtube_comments_summary.csv"

TARGET_MB = 120
MAX_PAGES_PER_VIDEO = 30
SLEEP_SEC = 0.05

df = pd.read_csv(VIDEO_STATS_CSV)

required_cols = ["video_id"]
for col in required_cols:
    if col not in df.columns:
        raise ValueError(f"필수 컬럼이 없습니다: {col}")

if "comment_count" in df.columns:
    df["comment_count"] = pd.to_numeric(df["comment_count"], errors="coerce").fillna(0)
    df = df.sort_values("comment_count", ascending=False)

df = df.drop_duplicates(subset=["video_id"]).reset_index(drop=True)

def file_size_mb(path):
    if not os.path.exists(path):
        return 0
    return os.path.getsize(path) / (1024 * 1024)

def get_comments(video_id, page_token=None):
    url = "https://www.googleapis.com/youtube/v3/commentThreads"
    params = {
        "part": "snippet,replies",
        "videoId": video_id,
        "maxResults": 100,
        "order": "relevance",
        "textFormat": "plainText",
        "key": AIzaSyAJ_x9HFan3L6VkwSsA9rmHKOGVsXKH1wI
    }
    if page_token:
        params["pageToken"] = page_token

    r = requests.get(url, params=params, timeout=30)
    return r

summary = []
total_comments = 0
skipped_videos = 0
quota_or_error = 0

with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for _, row in tqdm(df.iterrows(), total=len(df)):
        video_id = row["video_id"]
        keyword = row.get("keyword", "")
        category = row.get("category", "")
        title = row.get("title", "")
        channel_title = row.get("channel_title", "")

        page_token = None
        video_comment_count = 0

        for page in range(MAX_PAGES_PER_VIDEO):
            if file_size_mb(OUT_JSONL) >= TARGET_MB:
                break

            try:
                r = get_comments(video_id, page_token)
                if r.status_code != 200:
                    quota_or_error += 1
                    break

                data = r.json()
                items = data.get("items", [])

                if not items:
                    skipped_videos += 1
                    break

                for item in items:
                    snippet = item.get("snippet", {})
                    top = snippet.get("topLevelComment", {})
                    top_snippet = top.get("snippet", {})

                    record = {
                        "fetched_at": datetime.now(timezone.utc).isoformat(),
                        "keyword": keyword,
                        "category": category,
                        "video_id": video_id,
                        "video_title": title,
                        "channel_title": channel_title,
                        "comment_id": top.get("id"),
                        "comment_author": top_snippet.get("authorDisplayName"),
                        "comment_text": top_snippet.get("textDisplay"),
                        "comment_like_count": top_snippet.get("likeCount"),
                        "comment_published_at": top_snippet.get("publishedAt"),
                        "comment_updated_at": top_snippet.get("updatedAt"),
                        "reply_count": snippet.get("totalReplyCount"),
                        "raw_json": item
                    }

                    f.write(json.dumps(record, ensure_ascii=False) + "\n")
                    video_comment_count += 1
                    total_comments += 1

                page_token = data.get("nextPageToken")
                if not page_token:
                    break

                time.sleep(SLEEP_SEC)

            except Exception as e:
                quota_or_error += 1
                break

        summary.append({
            "video_id": video_id,
            "keyword": keyword,
            "category": category,
            "title": title,
            "channel_title": channel_title,
            "collected_comments": video_comment_count
        })

        if file_size_mb(OUT_JSONL) >= TARGET_MB:
            break

summary_df = pd.DataFrame(summary)
summary_df.to_csv(OUT_SUMMARY, index=False, encoding="utf-8-sig")

print("수집 완료")
print("raw jsonl:", OUT_JSONL, round(file_size_mb(OUT_JSONL), 2), "MB")
print("summary csv:", OUT_SUMMARY)
print("total_comments:", total_comments)
print("processed_videos:", len(summary))
print("skipped_videos:", skipped_videos)
print("quota_or_error:", quota_or_error)

import pandas as pd

summary = pd.read_csv("youtube_comments_summary.csv")
summary.head()

summary["collected_comments"].describe()

summary["collected_comments"].sum()

import requests
import pandas as pd
import json

API_KEY = "AIzaSyAJ_x9HFan3L6VkwSsA9rmHKOGVsXKH1wI"

df = pd.read_csv("youtube_video_stats_20keywords.csv")
df["comment_count"] = pd.to_numeric(df["comment_count"], errors="coerce").fillna(0)
df = df.sort_values("comment_count", ascending=False).drop_duplicates("video_id")

test_video_id = df.iloc[0]["video_id"]

print("테스트 video_id:", test_video_id)
print("영상 댓글 수:", df.iloc[0]["comment_count"])
print("영상 제목:", df.iloc[0].get("title", ""))

url = "https://www.googleapis.com/youtube/v3/commentThreads"
params = {
    "part": "snippet,replies",
    "videoId": test_video_id,
    "maxResults": 100,
    "order": "relevance",
    "textFormat": "plainText",
    "key": API_KEY
}

r = requests.get(url, params=params)

print("status_code:", r.status_code)
print(json.dumps(r.json(), ensure_ascii=False, indent=2)[:3000])

import os

for f in ["youtube_comments_raw.jsonl", "youtube_comments_summary.csv", "youtube_comments_error_log.csv"]:
    if os.path.exists(f):
        print(f, round(os.path.getsize(f) / (1024 * 1024), 2), "MB")

import os

for f in ["youtube_comments_raw.jsonl", "youtube_comments_summary.csv", "youtube_comments_error_log.csv"]:
    if os.path.exists(f):
        print(f, round(os.path.getsize(f) / (1024 * 1024), 2), "MB")

import pandas as pd

err = pd.read_csv("youtube_comments_error_log.csv")
err.tail(20)

import os

for f in [
    "youtube_comments_raw.jsonl",
    "youtube_comments_summary.csv",
    "youtube_comments_error_log.csv"
]:
    if os.path.exists(f):
        os.remove(f)
        print("삭제:", f)

import requests
import pandas as pd
import json

API_KEY = "AIzaSyAJ_x9HFan3L6VkwSsA9rmHKOGVsXKH1wI"

df = pd.read_csv("youtube_video_stats_20keywords.csv")
df["comment_count"] = pd.to_numeric(df["comment_count"], errors="coerce").fillna(0)
df = df.sort_values("comment_count", ascending=False).drop_duplicates("video_id").reset_index(drop=True)

test_video_id = df.iloc[0]["video_id"]

print("테스트 video_id:", test_video_id)
print("영상 댓글 수:", df.iloc[0]["comment_count"])
print("영상 제목:", df.iloc[0].get("title", ""))

url = "https://www.googleapis.com/youtube/v3/commentThreads"
params = {
    "part": "snippet,replies",
    "videoId": test_video_id,
    "maxResults": 100,
    "order": "relevance",
    "textFormat": "plainText",
    "key": API_KEY
}

r = requests.get(url, params=params)

print("status_code:", r.status_code)
data = r.json()
print(json.dumps(data, ensure_ascii=False, indent=2)[:3000])

import os
import json
import time
import requests
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timezone

API_KEY = "AIzaSyAJ_x9HFan3L6VkwSsA9rmHKOGVsXKH1wI"

VIDEO_STATS_CSV = "youtube_video_stats_20keywords.csv"
OUT_JSONL = "youtube_comments_raw.jsonl"
OUT_SUMMARY = "youtube_comments_summary.csv"
OUT_ERROR = "youtube_comments_error_log.csv"

TARGET_MB = 120
MAX_PAGES_PER_VIDEO = 50
SLEEP_SEC = 0.05

# 기존 파일 삭제
for f in [OUT_JSONL, OUT_SUMMARY, OUT_ERROR]:
    if os.path.exists(f):
        os.remove(f)

df = pd.read_csv(VIDEO_STATS_CSV)

if "video_id" not in df.columns:
    raise ValueError("video_id 컬럼이 없습니다.")

if "comment_count" in df.columns:
    df["comment_count"] = pd.to_numeric(df["comment_count"], errors="coerce").fillna(0)
    df = df.sort_values("comment_count", ascending=False)

df = df.drop_duplicates("video_id").reset_index(drop=True)

def file_size_mb(path):
    return os.path.getsize(path) / (1024 * 1024) if os.path.exists(path) else 0

def save_progress(summary, error_log):
    pd.DataFrame(summary).to_csv(OUT_SUMMARY, index=False, encoding="utf-8-sig")
    pd.DataFrame(error_log).to_csv(OUT_ERROR, index=False, encoding="utf-8-sig")

summary = []
error_log = []
total_comments = 0

with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for idx, row in tqdm(df.iterrows(), total=len(df)):
        video_id = row["video_id"]
        title = row.get("title", "")
        channel_title = row.get("channel_title", "")
        published_at = row.get("published_at", "")
        view_count = row.get("view_count", "")
        like_count = row.get("like_count", "")
        original_comment_count = row.get("comment_count", "")

        page_token = None
        video_comment_count = 0

        for page in range(MAX_PAGES_PER_VIDEO):
            if file_size_mb(OUT_JSONL) >= TARGET_MB:
                break

            url = "https://www.googleapis.com/youtube/v3/commentThreads"
            params = {
                "part": "snippet,replies",
                "videoId": video_id,
                "maxResults": 100,
                "order": "relevance",
                "textFormat": "plainText",
                "key": API_KEY
            }

            if page_token:
                params["pageToken"] = page_token

            try:
                r = requests.get(url, params=params, timeout=30)
                data = r.json()
            except Exception as e:
                error_log.append({
                    "video_id": video_id,
                    "status_code": "request_exception",
                    "reason": "request_exception",
                    "message": str(e)
                })
                break

            if r.status_code != 200:
                err = data.get("error", {})
                reason = err.get("errors", [{}])[0].get("reason", "unknown")
                message = err.get("message", "")

                error_log.append({
                    "video_id": video_id,
                    "status_code": r.status_code,
                    "reason": reason,
                    "message": message
                })

                if reason in ["quotaExceeded", "dailyLimitExceeded"]:
                    print("API quota 초과. 현재까지 저장하고 중단합니다.")
                    save_progress(summary, error_log)
                    raise SystemExit

                break

            items = data.get("items", [])

            if len(items) == 0:
                break

            for item in items:
                snippet = item.get("snippet", {})
                top = snippet.get("topLevelComment", {})
                top_snippet = top.get("snippet", {})

                record = {
                    "fetched_at": datetime.now(timezone.utc).isoformat(),
                    "video_id": video_id,
                    "video_title": title,
                    "channel_title": channel_title,
                    "video_published_at": published_at,
                    "video_view_count": view_count,
                    "video_like_count": like_count,
                    "video_comment_count": original_comment_count,
                    "comment_id": top.get("id"),
                    "comment_author": top_snippet.get("authorDisplayName"),
                    "comment_text": top_snippet.get("textDisplay"),
                    "comment_like_count": top_snippet.get("likeCount"),
                    "comment_published_at": top_snippet.get("publishedAt"),
                    "comment_updated_at": top_snippet.get("updatedAt"),
                    "reply_count": snippet.get("totalReplyCount"),
                    "raw_json": item
                }

                f.write(json.dumps(record, ensure_ascii=False) + "\n")
                video_comment_count += 1
                total_comments += 1

            page_token = data.get("nextPageToken")

            if not page_token:
                break

            time.sleep(SLEEP_SEC)

        summary.append({
            "video_id": video_id,
            "title": title,
            "channel_title": channel_title,
            "original_comment_count": original_comment_count,
            "collected_comments": video_comment_count
        })

        if idx % 10 == 0:
            print(
                "현재 크기:",
                round(file_size_mb(OUT_JSONL), 2),
                "MB / 총 수집 댓글:",
                total_comments,
                "/ 처리 영상:",
                idx + 1
            )
            save_progress(summary, error_log)

        if file_size_mb(OUT_JSONL) >= TARGET_MB:
            print("목표 용량 도달:", round(file_size_mb(OUT_JSONL), 2), "MB")
            break

save_progress(summary, error_log)

print("수집 완료")
print("raw jsonl:", round(file_size_mb(OUT_JSONL), 2), "MB")
print("summary csv:", OUT_SUMMARY)
print("error log:", OUT_ERROR)
print("total_comments:", total_comments)
print("processed_videos:", len(summary))
print("error_count:", len(error_log))

from google.colab import files

files.download("youtube_comments_raw.jsonl")
files.download("youtube_comments_summary.csv")
files.download("youtube_comments_error_log.csv")



